### ISSUE TITLE
Parallelized 40x extraction script for 20x

### ISSUE THREAD

**Issue by andrewrech** [SBU-BMI/quip_cancer_segmentation#2]
@hansbu 

Thanks for making this so clear.

 I would like to preprocess 20x and 40x extraction outside docker.

I just made a couple edits to your 40x extraction script on my fork. Does this look ok?

https://github.com/immune-health/quip_cancer_segmentation/commit/201d041c44e105e469826870d3ce2627d9c01cbe

**Comment by hansbu** [comment]
When I extract the large tiles at 40X, it is 2100x2100 which is multiple of 350 (350x350 is the size of individual patch at 40X). If you want to extract at 20X, you have to make it multiple of 350/2=175, for example, 2100/2=1050. I see that you want to make it the same size as the TIL tiles. Hence, you can set it to be the Least Common Multiple of 100 and 175, let say 700 or 1400.

Another problem, if you extract the patch at 20X, you have to change the APS value in prediction/tumor_pred/pred.py and prediction/color/color_stats.pu from 350 to 175

**Comment by andrewrech** [comment]
Thanks!

**Comment by andrewrech** [comment]
ps @hansbu we'll do this at 40x (just  want to extract at 20x at the same time for classification)

**Comment by hansbu** [comment]
@andrewrech: I see. Sure, it'll work faster than our previous code since I used multi threading, you can increase the number of threads in line 79 if you have more CPU resources.
